# Generated by Django 5.0.2 on 2024-02-15 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, default='https://images.dog.ceo/breeds/bulldog-english/jager-2.jpg', max_length=100)),
                ('biography', models.CharField(blank=True, default="Hello, I'm a scoonti user", max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]