# Generated by Django 5.0.1 on 2024-01-25 16:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(max_length=100)),
                ('zone_image', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='cities.city')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('size', models.IntegerField()),
                ('apartment_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), blank=True, size=None)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='cities.zone')),
            ],
        ),
    ]
